### ISSUE TITLE
“Social media shenanigans” - missing content

### ISSUE THREAD

**Issue by eragmus** [kosinusbch/cult-of-craig#2]
It is available here:
https://github.com/psztorc/cult-of-craig/blob/master/sock-puppets.md

This above repo was forked from the original, and also appears to be the most updated version (last commit 5 months ago) still available, before Andreas Brekken sold out to CSW and deleted his repo (https://github.com/CultOfCraig/cult-of-craig).

**Comment by kosinusbch** [comment]
Thanks, added back the link to the sockpuppets page, though it seems like a bit of a pain to maintain given the sheer amount of people involved at this point
